# Generated by Django 5.2.8 on 2025-12-01 18:29

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAccount',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('api_key', models.CharField(max_length=100)),
                ('api_secret', models.CharField(max_length=100)),
                ('access_token', models.CharField(blank=True, max_length=256, null=True)),
                ('is_live_trading_enabled', models.BooleanField(default=False, verbose_name='Client Kill Switch')),
                ('is_broker_approved', models.BooleanField(default=False, verbose_name='Broker/Admin Approved')),
                ('max_daily_profit', models.FloatField(default=10000.0, verbose_name='Max Profit to Stop Trading')),
                ('max_daily_loss', models.FloatField(default=-5000.0, verbose_name='Max Loss to Stop Trading')),
                ('no_new_entry_after', models.TimeField(default=datetime.time(15, 0), verbose_name='No New Entry After')),
                ('square_off_time', models.TimeField(default=datetime.time(15, 15), verbose_name='Daily Square Off Time')),
            ],
        ),
        migrations.CreateModel(
            name='TradeSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('instrument_token', models.CharField(help_text='Zerodha Instrument Token', max_length=20, unique=True)),
                ('exchange', models.CharField(choices=[('NSE', 'NSE'), ('BSE', 'BSE')], max_length=10)),
                ('segment', models.CharField(choices=[('EQ', 'Equity'), ('FUT', 'FUT'), ('OPT', 'OPT')], default='EQ', max_length=10)),
                ('qty_type', models.CharField(choices=[('ABS', 'Absolute'), ('FORMULA', 'Formula')], default='ABS', max_length=10)),
                ('absolute_quantity', models.IntegerField(default=1)),
                ('exposure_formula', models.TextField(blank=True, help_text='Exposure formula based on capital/margin.', null=True)),
                ('price_band_color', models.CharField(choices=[('BLUE', 'Blue F&O (1% order rule)'), ('GREEN', '20% (Equity)'), ('BROWN', '10% (Equity)'), ('RED', '5% (Equity)')], default='GREEN', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Trade Symbols (Scrips)',
            },
        ),
        migrations.CreateModel(
            name='TradeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('entry_price', models.FloatField()),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('realized_pnl', models.FloatField(default=0.0)),
                ('targets', models.JSONField(default=dict, help_text='Calculated T1-T10, S1-S10, TSL levels.')),
                ('entry_order_id', models.CharField(blank=True, max_length=50)),
                ('squareoff_order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('client_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.clientaccount')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.tradesymbol')),
            ],
        ),
    ]
