# Generated by Django 5.2.8 on 2025-12-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
