# Generated by Django 5.2.8 on 2025-12-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_clientaccount_is_phone_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
