# Generated by Django 5.2.8 on 2025-12-03 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_clientaccount_is_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='LadderState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('current_mode', models.CharField(choices=[('BUY', 'Buy Ladder'), ('SELL', 'Sell Ladder'), ('STOPPED', 'Stopped')], default='STOPPED', max_length=10)),
                ('entry_price', models.FloatField(default=0.0)),
                ('last_add_price', models.FloatField(default=0.0)),
                ('extreme_price', models.FloatField(default=0.0)),
                ('current_qty', models.IntegerField(default=0)),
                ('level_count', models.IntegerField(default=0)),
                ('trade_capital', models.FloatField(default=10000.0)),
                ('increase_pct', models.FloatField(default=1.0)),
                ('tsl_pct', models.FloatField(default=1.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.clientaccount')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.tradesymbol')),
            ],
            options={
                'unique_together': {('client', 'symbol')},
            },
        ),
    ]
