# Generated by Django 5.2.8 on 2025-12-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_chartinkalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='ladderstate',
            name='entry_type',
            field=models.CharField(choices=[('QUANTITY', 'Fixed Quantity'), ('CAPITAL', 'Fixed Capital')], default='CAPITAL', help_text='Choose if the initial order is based on quantity or total capital', max_length=10),
        ),
        migrations.AddField(
            model_name='ladderstate',
            name='fixed_quantity',
            field=models.IntegerField(default=0, help_text='Used if entry_type is QUANTITY'),
        ),
        migrations.AlterField(
            model_name='ladderstate',
            name='trade_capital',
            field=models.FloatField(default=10000.0, help_text='Used if entry_type is CAPITAL'),
        ),
    ]
