# Generated by Django 5.2.8 on 2025-12-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_ladderstate_entry_type_ladderstate_fixed_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ladderstate',
            name='ladder_type',
            field=models.CharField(choices=[('MARKET', 'Market Ladder'), ('CHARTINK', 'Chartink Ladder')], default='MARKET', max_length=20),
        ),
    ]
