"""
Django settings for Algosystem project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv  # <-- Import this


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = os.getenv('SECRET_KEY')
SECRET_KEY = 'django-insecure-pri(y4t=-9)%cz@_*08o_w=c8&+c1fb99v^#vb3!%-h^p1)&n+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = 'True'

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'trading',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Algosystem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Algosystem.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- REDIS CONFIGURATION (Cache & Message Broker) ---

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    # The 'ticks' cache must be defined for your code to work
    "ticks": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/2", # Using DB 2 for ticks
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
             # IMPORTANT: If you use a prefix, keys('*') breaks. 
             # But with the fix above (get_many), prefixes won't matter.
        }
    }
}


# --- KITE CONNECT COMMON CONFIGURATION ---
# Kite API key/secret are stored per-user, but the general redirect URL is global.
KITE_REDIRECT_URL = "http://127.0.0.1:8000/kite/callback"

# --- TRADING CONSTANTS ---
SQURE_OFF_TIME = "15:15:00" 

MAX_SCRIPS_LIMIT = 75 

# Tick size settings (for automatic adjustment)
TICK_SIZES = {
    'NSE': 0.05,
}

# --- AUTHENTICATION REDIRECTS ---
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard' 
LOGOUT_REDIRECT_URL = 'login'   

# --- CELERY SETTINGS ---
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Redis DB 0 for Broker
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Kolkata'

# --- CELERY BEAT SCHEDULE ---
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'fetch-instruments-every-morning': {
        'task': 'trading.tasks.fetch_instruments_task', # Task name
        'schedule': crontab(hour=12, minute=9),          # Daily at 9:00 AM
        # Testing ke liye har minute chalana ho to:
        # 'schedule': crontab(minute='*'), 
    },
}


# --- 1. REAL EMAIL CONFIGURATION (Gmail) ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')        
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD') 


# 1. STOCK UNIVERSE (For Scanner)
MONITORED_SYMBOLS = ['ACMESOLAR', 'LAURUSLABS', 'VIJAYA', 'CHENNPETRO', 'ECLERX', 'AADHARHFC', 
'ADANIGREEN', 'MPHASIS', 'SHRIRAMFIN', 'AMBER', 'CIPLA', 'SYRMA', 'DABUR', 
'PAYTM', 'MEDANTA', 'RAMCOCEM', 'COFORGE', 'AFFLE', 'GLAND', 'INTELLECT', 
'JPPOWER', 'MOTHERSON', 'SBFC', 'IGL', 'VBL', 'ABSLAMC', 'ANANDRATHI', 'TIMKEN',
'POLYCAB', 'HEROMOTOCO', 'POONAWALLA', 'NTPCGREEN', 'SYNGENE', 'KEI', 'NAVINFLUOR',
'PEL', 'KIMS', 'ASTRAZEN', 'PPLPHARMA', 'RHIM', 'ASIANPAINT', 'CAPLIPOINT', 'BOSCHLTD', 
'HINDUNILVR', 'TORNTPOWER', 'TATAPOWER', 'SAPPHIRE', 'JSL', 'TVSMOTOR', 'CROMPTON', 'SBILIFE',
'KALYANKJIL', 'TATACONSUM', 'UPL', 'ICICIBANK', 'ASHOKLEY', 'ALKEM', 'TORNTPHARM', 'SIEMENS',
'JUBLINGREA', 'DRREDDY', 'NEWGEN', 'HONASA', 'MAPMYINDIA', 'SRF', 'DELHIVERY', 'SCHAEFFLER',
'MARICO', 'LUPIN', 'APLLTD', 'JSWHL', 'CESC', 'EXIDEIND', 'EIDPARRY', 'POLICYBZR', 'GRASIM',
'HFCL', 'BRITANNIA', 'HEG', 'ZENSARTECH', 'PNBHOUSING', 'PAGEIND', 'KAJARIACER', 'NEULANDLAB', 
'BERGEPAINT', 'PTCIL', 'VOLTAS', 'DIXON', 'JSWSTEEL', 'SUPREMEIND', 'ADANIPOWER', 'NHPC', 'ATUL',
'BALKRISIND', 'UNITDSPR', 'HDFCBANK', 'OFSS', 'LINDEINDIA', 'BPCL', 'IOC', 'EIHOTEL', 'LICI', 
'HINDPETRO', 'GODIGIT', 'AUROPHARMA', 'JSWENERGY', 'ZYDUSLIFE', 'JBCHEPHARM', 'JUSTDIAL', 'WOCKPHARMA',
'POWERGRID', 'CUMMINSIND', 'JUBLPHARMA', 'FORTIS', 'ALIVUS', 'ITC', 'ADANIENSOL', 'KEC', 'HDFCAMC', 
'MAHABANK', 'ESCORTS', 'MGL', 'TBOTEK', 'OLAELEC', 'SUNPHARMA', 'IDFCFIRSTB', 'BAJAJ-AUTO', 'ATGL',
'INFY', 'TATACOMM', 'NH', 'USHAMART', 'ULTRACEMCO', 'METROPOLIS', 'PETRONET', 'TATAINVEST', 'NTPC',
'HDFCLIFE', 'PIIND', 'INDHOTEL', 'BSE', 'GODREJCP', 'MFSL', 'CCL', 'KARURVYSYA', 'INDIAMART', 'CANBK', 
'ONGC', 'GPIL', 'SWIGGY', 'PERSISTENT', 'KPRMILL', 'GMRAIRPORT', 'CENTRALBK', 'JKCEMENT', 'UCOBANK', 
'RELIANCE', 'COLPAL', 'CLEAN', 'AARTIIND', 'BALRAMCHIN', 'EMCURE', 'BATAINDIA', 'GLENMARK', 'LTTS', 
'SOLARINDS', 'GRAPHITE', 'SONACOMS', 'TATAMOTORS', 'BAJAJFINSV', 'MUTHOOTFIN', 'BAYERCROP', 'DIVISLAB', 
'BAJAJHLDNG', 'GILLETTE', 'MINDACORP', 'MARUTI', 'RITES', 'INDIACEM', 'TATAELXSI', 'THERMAX', 'AEGISLOG',
'AKUMS', 'CRAFTSMAN', 'LT', 'JUBLFOOD', 'SJVN', 'NBCC', 'TRITURBINE', 'CYIENT', 'SUMICHEM', 'PIDILITIND',
'DCMSHRIRAM', 'CENTURYPLY', 'IDEA', 'RBLBANK', 'IRFC', 'BLUESTARCO', 'ABFRL', 'GODREJAGRO', 'CGPOWER', '360ONE',
'COALINDIA', 'TATACHEM', 'TECHM', 'ICICIPRULI', 'AMBUJACEM', 'INDIGO', 'STARHEALTH', 'TRENT', 'CHOLAFIN', 'ADANIENT',
'ASAHIINDIA', 'GRANULES', 'GSPL', 'IFCI', 'DALBHARAT', 'BLS', 'APOLLOTYRE', 'FINCABLES', 'ICICIGI', 'FIRSTCRY', 'MASTEK',
'ACE', 'EICHERMOT', 'NMDC', 'GICRE', 'LTIM', 'ASTERDM', 'LATENTVIEW', 'FEDERALBNK', 'HAL', 'INOXWIND', 'RAINBOW', 'BEL',
'LEMONTREE', 'HINDALCO', 'AIAENG', 'AXISBANK', 'NYKAA', 'NIVABUPA', 'M&M', 'ETERNAL', 'BANKBARODA', 'AUBANK', 'MRF',
'3MINDIA', 'CERA', 'AJANTPHARM', 'BHARATFORG', 'SONATSOFTW', 'FINPIPE', 'JIOFIN', 'SHYAMMETL', 'IGIL', 'MSUMI', 'DMART',
'PHOENIXLTD', 'SBIN', 'UTIAMC', 'SARDAEN', 'BBTC', 'PNB', 'PCBL', 'TARIL', 'TATASTEEL', 'SHREECEM', 'IDBI', 'YESBANK', 'ACC', 
'ERIS', 'KPIL', 'COROMANDEL', 'VEDL', 'WHIRLPOOL', 'GODFRYPHLP', 'NCC', 'RADICO', 'DEVYANI', 'CANFINHOME', 'CONCORDBIO', 'ENDURANCE',
'BAJAJHFL', 'IKS', 'APOLLOHOSP', 'ADANIPORTS', 'CONCOR', 'HAVELLS', 'TATATECH', 'CEATLTD', 'BHARTIHEXA', 'HCLTECH', 'GODREJIND', 'NAUKRI',
'INDIANB', 'CASTROLIND', 'PRAJIND', 'BANDHANBNK', 'SWANENERGY', 'M&MFIN', 'BANKINDIA', 'BIOCON', 'UBL', 'JYOTHYLAB', 'SAMMAANCAP', 'LTF', 
'DEEPAKFERT', 'RTNINDIA', 'WIPRO', 'AWL', 'DEEPAKNTR', 'ALKYLAMINE', 'TCS', 'PGEL', 'INDGN', 'CUB', 'RAYMONDLSL', 'FSL', 'GNFC', 'SUNTV', 
'KANSAINER', 'FLUOROCHEM', 'BHEL', 'HINDZINC', 'TTML', 'NESTLEIND', 'NUVAMA', 'CGCL', 'MAXHEALTH', 'KIRLOSENG', 'PATANJALI', 'SWSOLAR', 'JKTYRE',
'ABB', 'LTFOODS', 'SKFINDIA', 'TRIVENI', 'GUJGASLTD', 'NSLNISP', 'CHAMBLFERT', 'UNOMINDA', 'SOBHA', 'MOTILALOFS', 'ALOKINDS', 'COHANCE', 
'KFINTECH', 'SAILIFE', 'SUNDRMFAST', 'LALPATHLAB', 'PNCINFRA', 'RRKABEL', 'NAVA', 'IRB', 'TECHNOE', 'IPCALAB', 'ANANTRAJ', 'OIL', 'ELECON',
'SIGNATURE', 'PFIZER', 'GAIL', 'JYOTICNC', 'NLCINDIA', 'WELSPUNLIV', 'IOB', 'AAVAS', 'UNIONBANK', 'IREDA', 'GLAXO', 'DOMS', 'KNRCON', 'HUDCO',
'RCF', 'GVT&D', 'RECLTD', 'PVRINOX', 'ASTRAL', 'ROUTE', 'HAPPSTMNDS', 'LLOYDSME', 'CHALET', 'SCI', 'TITAN', 'CAMPUS', 'ARE&M', 'IRCTC',
'FIVESTAR', 'KPITTECH', 'HYUNDAI', 'RKFORGE', 'ZFCVINDIA', 'SCHNEIDER', 'EMAMILTD', 'SUNDARMFIN', 'WELCORP', 'TITAGARH', 'NAM-INDIA', 'AIIL',
'POWERINDIA', 'JINDALSTEL', 'PFC', 'TRIDENT', 'BHARTIARTL', 'TIINDIA', 'BDL', 'MANKIND', 'MAHSEAMLES', 'BSOFT', 'NETWORK18', 'CREDITACC',
'INDUSTOWER', 'APLAPOLLO', 'RAYMOND', 'MANAPPURAM', 'LICHSGFIN', 'BIKAJI', 'GPPL', 'ABCAPITAL', 'RENUKA', 'JBMA', 'KIRLOSBROS', 'SAREGAMA',
'HBLENGINE', 'REDINGTON', 'ABREL', 'APTUS', 'IRCON', 'ABBOTINDIA', 'INDUSINDBK', 'WESTLIFE', 'NATCOPHARM', 'JSWINFRA', 'VTL', 'CARBORUNIV',
'JWL', 'FACT', 'COCHINSHIP', 'RVNL', 'INOXINDIA', 'OLECTRA', 'GESHIP', 'DBREALTY', 'WAAREEENER', 'APARINDS', 'JINDALSAW', 'ITI', 'MAZDOCK', 
'CRISIL', 'GRSE', 'HSCL', 'NATIONALUM', 'BLUEDART', 'KAYNES', 'JMFINANCIL', 'AFCONS', 'NIACL', 'SAIL', 'BASF', 'MMTC', 'GRAVITA', 'PREMIERENE', 'IIFL', 
'PRESTIGE', 'BAJFINANCE', 'BEML', 'CAMS', 'MANYAVAR', 'MCX', 'HINDCOPPER', 'DATAPATTNS', 'VGUARD', 'ZEEL',
'HONAUT', 'RAILTEL', 'OBEROIRLTY', 'SUZLON', 'TEJASNET', 'ANGELONE', 'IEX', 'DLF', 'POLYMED', 'J&KBANK', 'BRIGADE', 'MRPL', 'ELGIEQUIP', 'CHOLAHLDNG',
'RPOWER', 'ZENTEC', 'VMM', 'GODREJPROP', 'SAGILITY', 'CDSL', 'ENGINERSIN', 'NETWEB', 'TANLA', 'GMDCLTD', 'SBICARD', 'LODHA', 'KOTAKBANK', 'HOMEFIRST']


# 2. F&O LIST (For Blue Highlighting)
FNO_LIST = [
    "360ONE", "ABB", "APLAPOLLO", "AUBANK", "ADANIENSOL", "ADANIENT", "ADANIGREEN", "ADANIPORTS",
    "ABCAPITAL", "ALKEM", "AMBER", "AMBUJACEM", "ANGELONE", "APOLLOHOSP", "ASHOKLEY", "ASIANPAINT",
    "ASTRAL", "AUROPHARMA", "DMART", "AXISBANK", "BSE", "BAJAJ-AUTO", "BAJFINANCE", "BAJAJFINSV",
    "BANDHANBNK", "BANKBARODA", "BANKINDIA", "BDL", "BEL", "BHARATFORG", "BHEL", "BPCL",
    "BHARTIARTL", "BIOCON", "BLUESTARCO", "BOSCHLTD", "BRITANNIA", "CGPOWER", "CANBK", "CDSL",
    "CHOLAFIN", "CIPLA", "COALINDIA", "COFORGE", "COLPAL", "CAMS", "CONCOR", "CROMPTON", "CUMMINSIND",
    "CYIENT", "DLF", "DABUR", "DALBHARAT", "DELHIVERY", "DIVISLAB", "DIXON", "DRREDDY", "ETERNAL",
    "EICHERMOT", "EXIDEIND", "NYKAA", "FORTIS", "GAIL", "GMRAIRPORT", "GLENMARK", "GODREJCP",
    "GODREJPROP", "GRASIM", "HCLTECH", "HDFCAMC", "HDFCBANK", "HDFCLIFE", "HFCL", "HAVELLS",
    "HEROMOTOCO", "HINDALCO", "HAL", "HINDPETRO", "HINDUNILVR", "HINDZINC", "POWERINDIA", "HUDCO",
    "ICICIBANK", "ICICIGI", "ICICIPRULI", "IDFCFIRSTB", "IIFL", "ITC", "INDIANB", "IEX", "IOC",
    "IRCTC", "IRFC", "IREDA", "IGL", "INDUSTOWER", "INDUSINDBK", "NAUKRI", "INFY", "INOXWIND",
    "INDIGO", "JINDALSTEL", "JSWENERGY", "JSWSTEEL", "JIOFIN", "JUBLFOOD", "KEI", "KPITTECH",
    "KALYANKJIL", "KAYNES", "KFINTECH", "KOTAKBANK", "LTF", "LICHSGFIN", "LTIM", "LT", "LAURUSLABS",
    "LICI", "LODHA", "LUPIN", "M&M", "MANAPPURAM", "MANKIND", "MARICO", "MARUTI", "MFSL",
    "MAXHEALTH", "MAZDOCK", "MPHASIS", "MCX", "MUTHOOTFIN", "NBCC", "NCC", "NHPC", "NMDC", "NTPC",
    "NATIONALUM", "NESTLEIND", "NUVAMA", "OBEROIRLTY", "ONGC", "OIL", "PAYTM", "OFSS", "POLICYBZR",
    "PGEL", "PIIND", "PNBHOUSING", "PAGEIND", "PATANJALI", "PERSISTENT", "PETRONET", "PIDILITIND",
    "PPLPHARMA", "POLYCAB", "PFC", "POWERGRID", "PRESTIGE", "PNB", "RBLBANK", "RECLTD", "RVNL",
    "RELIANCE", "SBICARD", "SBILIFE", "SHREECEM", "SRF", "SAMMAANCAP", "MOTHERSON", "SHRIRAMFIN",
    "SIEMENS", "SOLARINDS", "SONACOMS", "SBIN", "SAIL", "SUNPHARMA", "SUPREMEIND", "SUZLON",
    "SYNGENE", "TATACONSUM", "TITAGARH", "TVSMOTOR", "TCS", "TATAELXSI", "TMPV", "TATAPOWER",
    "TATASTEEL", "TATATECH", "TECHM", "FEDERALBNK", "INDHOTEL", "PHOENIXLTD", "TITAN", "TORNTPHARM",
    "TORNTPOWER", "TRENT", "TIINDIA", "UNOMINDA", "UPL", "ULTRACEMCO", "UNIONBANK", "UNITDSPR",
    "VBL", "VEDL", "IDEA", "VOLTAS", "WIPRO", "YESBANK", "ZYDUSLIFE"
]


# 3. LADDER STRATEGY SETTINGS
LADDER_SETTINGS = {
    'TRADE_CAPITAL': 10000.0,      
    'INCREASE_THRESHOLD_PCT': 1.0, 
    'TSL_PCT': 1.0,                
    'SQUARE_OFF_TIME': "15:15:00",
    'MAX_PYRAMID_LEVELS': 10       
}


